In [23]:
##################### Numpy Array Exercise  ########################### 

In [24]:
import numpy as np
arr=np.array([1,1,2,32]) #1D array
print(arr)

[ 1  1  2 32]


In [25]:
##checking the numpy version
print(np.__version__)

1.19.5


In [26]:
arr_2d=np.array([[1,2,3,4],[1,3,4,5]])##2D array
print(arr_2d)

[[1 2 3 4]
 [1 3 4 5]]


In [27]:
arr_3d=np.array([[[1,2,3,4],[1,4,8,9],[3,4,56,6]]])
print(str(arr_3d)+"The diminsion:"+str(arr_3d.ndim))

[[[ 1  2  3  4]
  [ 1  4  8  9]
  [ 3  4 56  6]]]The diminsion:3


In [28]:
#################------indexing-------------------###########################

In [29]:
a=arr[2]## getting value from the 1D array 
print(str(a)+":index 2 from the array called arr.")


2:index 2 from the array called arr.


In [30]:
b=arr_2d[0,3]## geting the value from the index 0,3 from 2d Array
print(str(b))

4


In [31]:
######--------Negative indexing---------######################

In [32]:
N_a=arr[-1]##negative indexing of the array
print(str(N_a))

32


In [33]:
######-----------------Sliceing Array------------------------------######

In [34]:
S_a=arr[0:3]#sliceing the array to make new array
S_b=arr[0:3:2]
print(str(S_a))
print(str(S_b))
print(type(S_a))

[1 1 2]
[1 2]
<class 'numpy.ndarray'>


In [35]:
S_a1=arr_2d[0:2,0:2]##slice 2D array to make new array
print(S_a1)
print(arr.shape)
print(arr_2d.shape)
print(arr_3d.shape)


[[1 2]
 [1 3]]
(4,)
(2, 4)
(1, 3, 4)


In [36]:
###################------Array Reshape-------##################################

In [37]:
arr_1=arr.reshape(2,2)##array reshaping into new array 1D into 2D
print(arr_1)

[[ 1  1]
 [ 2 32]]


In [38]:
arr_2=arr_2d.reshape(2,2,2)#Reshapeing into 3d array from 2D array
print(arr_2,arr_2.ndim)


[[[1 2]
  [3 4]]

 [[1 3]
  [4 5]]] 3
